/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263.catalog;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import edu.isu.cs.cs2263.catalog.Course;

import java.util.List;

public class App extends Application {
    private static final int WINDOW_WIDTH = 650;
    private static final int WINDOW_HEIGHT = 300;
    private ComboBox<Department> cbDepartment;
    private Button btnAddCourse;
    private TextField txtCourseNumber;
    private TextField txtCourseName;
    private TextField txtCourseCredits;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Application.launch(args);
        System.out.println(new App().getGreeting());
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Course Catalog");
        GridPane gpInput = createInputBox();
        // add error message box under gpInput.
        // add filter buttons and exit button

        Scene scene = new Scene(gpInput, WINDOW_WIDTH, WINDOW_HEIGHT);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private GridPane createInputBox() {
        Label lblDepartment = new Label("Department");
        cbDepartment = createDepartmentComboBox();
        Label lblCourseNumber = new Label("Course #");
        txtCourseNumber = new TextField("");
        Label lblCourseName = new Label("Course Name");
        txtCourseName = new TextField("");
        Label lblCourseCredits = new Label("Credits");
        txtCourseCredits = new TextField("");
        Label lblAddCourse = new Label("");
        btnAddCourse = new Button("Add Course");

        VBox vbDepartment = new VBox(lblDepartment, cbDepartment);
        vbDepartment.setPadding(new javafx.geometry.Insets(0, 3, 0, 3));
        VBox vbCourseNumber = new VBox(lblCourseNumber, txtCourseNumber);
        vbCourseNumber.setPadding(new javafx.geometry.Insets(0, 3, 0, 3));
        VBox vbCourseName = new VBox(lblCourseName, txtCourseName);
        vbCourseName.setPadding(new javafx.geometry.Insets(0, 3, 0, 3));
        VBox vbCourseCredits = new VBox(lblCourseCredits, txtCourseCredits);
        vbCourseCredits.setPadding(new javafx.geometry.Insets(0, 3, 0, 3));
        VBox vbAddCourse = new VBox(lblAddCourse, btnAddCourse);
        vbAddCourse.setPadding(new javafx.geometry.Insets(0, 3, 0, 3));

        GridPane grid = new GridPane();
        ColumnConstraints col1 = new ColumnConstraints();
        col1.setPercentWidth(24);
        ColumnConstraints col2 = new ColumnConstraints();
        col2.setPercentWidth(10);
        ColumnConstraints col3 = new ColumnConstraints();
        col3.setPercentWidth(42);
        ColumnConstraints col4 = new ColumnConstraints();
        col4.setPercentWidth(10);
        ColumnConstraints col5 = new ColumnConstraints();
        col5.setPercentWidth(14);
        grid.getColumnConstraints().addAll(col1, col2, col3, col4, col5);

        grid.add(vbDepartment, 0, 0);
        grid.add(vbCourseNumber, 1, 0);
        grid.add(vbCourseName, 2, 0);
        grid.add(vbCourseCredits, 3, 0);
        grid.add(vbAddCourse, 4, 0);
        grid.setPadding(new javafx.geometry.Insets(6, 3, 6, 3));

        return grid;
    }

    private ComboBox<Department> createDepartmentComboBox() {
        ComboBox<Department> out = new ComboBox<>();
        Department[] departments = Course.getDepartments();
        for (Department d : departments) {
            out.getItems().add(d);
        }
        return out;
    }
}
